---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: taruns2501/athrey:latest
    container_name: app_container
    ports: 3000:3000
  environment:
    NODE_ENV: production
  networks: web