networks:
  web:
    external: true
  internal:
    driver: bridge

services:
  athrey_bdev:
    build: .
    container_name: athrey_bdev
    image: athrey_bdev:latest
    environment:
      NODE_ENV: development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.athrey_bdev.rule=Host(`athrey-bdev.edalytics.com`)"
      - "traefik.http.routers.athrey_bdev.tls=true"
      - "traefik.http.routers.athrey_bdev.tls.certresolver=lets-encrypt"
      - "traefik.http.middlewares.https-redirect.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.services.athrey_bdev.loadbalancer.server.port=3100"
    networks:
      - web
      - internal
    restart: unless-stopped
    ports:
      - "3000:3000"
    command: >
      node src/index.js

  athrey_dredis:
    image: bitnami/redis:latest
    container_name: athrey_dredis
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL"
      REDIS_REPLICATION_MODE: master
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.athrey_dredis.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.athrey_dredis.entryPoints=redis"
      - "traefik.tcp.services.athrey_dredis.loadbalancer.server.port=6379"
    networks:
      - internal
    ports:
      - "6379:6379"
