name: CICD for Athrey

on:
  push:
    branches:
      - main
      - dev
      - uat

jobs:
  Development-Image:
    runs-on: ubuntu-latest
    name: Building Development APP
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setting up Docker
        uses: docker/setup-buildx-action@v2

      - name: Building Docker image for Development
        run: |
          docker compose build athrey_bdev

  UAT-Image:
    runs-on: ubuntu-latest
    name: Building UAT APP
    if: github.ref == 'refs/heads/uat'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setting up Docker
        uses: docker/setup-buildx-action@v2

      - name: Building Docker image for UAT
        run: |
          docker compose build athrey_bdev

  Production-Image:
    runs-on: ubuntu-latest
    name: Building Production APP
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setting up Docker
        uses: docker/setup-buildx-action@v2

      - name: Building Docker image for Production
        run: |
          docker compose build athrey_bdev

  Development-Container:
    runs-on: ubuntu-latest
    name: Deploying Development
    needs: Development-Image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploying Docker containers for Development
        run: |
          docker compose up -d athrey_bdev athrey_dredis

  UAT-Container:
    runs-on: ubuntu-latest
    name: Deploying UAT
    needs: UAT-Image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploying Docker containers for UAT
        run: |
          docker compose up -d athrey_bdev athrey_dredis

  Production-Container:
    runs-on: ubuntu-latest
    name: Deploying Production
    needs: Production-Image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploying Docker containers for Production
        run: |
          docker compose up -d athrey_bdev athrey_dredis

  cleaning:
    runs-on: ubuntu-latest
    name: Cleaning Cache
    needs:
      - Development-Container
      - Production-Container

    steps:
      - name: Cleaning Docker Cache
        run: |
          docker system prune -a -f
